### ISSUE TITLE
Cannot execute binary in Windows (11)

### ISSUE THREAD

**Issue by bobbyharsono** [Graylog2/graylog-project-cli#32]
1. download binary
2. copy to a folder and include the folder in env path
3. execute graylog-project bootstrap github://Graylog2/graylog-project.git

Had removed the extension as well as trying ".bat" or ".exe" as extension

Cannot execute command since WIndow will ask how to open this file? The README says the binary would have no extension 
(cp graylog-project.linux $HOME/bin/graylog-project)

Or Window currently not supported? 

![image](https://user-images.githubusercontent.com/25737227/193518990-efbc97a0-8a0e-4cf1-805e-eb22d11847ef.png)

Thank you

**Comment by bernd** [comment]
We are now shipping a Windows binary. See: https://github.com/Graylog2/graylog-project-cli/releases
