### ISSUE TITLE
The graylog-project (CLI) bootstrap doesn't work with https mode repositories.

### ISSUE THREAD

**Issue by FelipeEcker** [Graylog2/graylog-project-cli#4]
Hi guys,
When i call: graylog-project-cli bootstrap <repository> [flags]

$ graylog-project-cli bootstrap https://github.com/Graylog2/graylog-project.git -H
    (or)
$ graylog-project-cli bootstrap https://github.com/Graylog2/graylog-project.git -U

...so the cli ignores my option for https clone and force one git clone under ssh type:

$ graylog-project bootstrap https://github.com/Graylog2/graylog-project.git -H
    git clone git@github.com:Graylog2/graylog-project.git graylog-project
    Git stderr:
    Error executing: git [clone git@github.com:Graylog2/graylog-project.git graylog-project] (exit status 128)

**Comment by bernd** [comment]
@FelipeEcker Thank you for the report!

The `-H` flag is obsolete and does not work. I will fix the tool to use the transport of the graylog-project URL argument to bootstrap.

- `graylog-project bootstrap https://github.com/Graylog2/graylog-project.git` will clone all repositories via HTTPS
- `graylog-project bootstrap git@github.com:Graylog2/graylog-project.git` will clone all repositories via SSH

**Comment by bernd** [comment]
@FelipeEcker We released a new version: https://github.com/Graylog2/graylog-project-cli/releases/tag/0.16.1
