### ISSUE TITLE
how to clone older version of graylog 

### ISSUE THREAD

**Issue by debasish283** [Graylog2/graylog-project-cli#5]
is there any way that i can download older graylog version

**Comment by joschi** [comment]
@debasish283 You can provide the branch, tag, or commit SHA-1 in the `manifest` attribute in the manifest files, see https://github.com/Graylog2/graylog-project/blob/783de2791093b9eed52a58f0b6c42261bdf16d8d/manifests/2.2.json for an example.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
